---
  - name: Add 48755 SSH port, and keep port 22 only for Ansible
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '#Port\ 22'
      line: | 
        Port 22
        Port 48755

  - name: Disable SSH Root Login
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '#PermitRootLogin\ yes'
      line: PermitRootLogin no

  - name: Restart SSH
    systemd:
      state: restarted
      name: sshd
      enabled: yes